name: Daily Backup Task

on:
  schedule:
    - cron: '0 0 * * *'  # This means the task will run every day at midnight

jobs:
  backup:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Run PowerShell backup script
        run: |
          pwsh ./backup-script.ps1
